name: .NET

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        dotnet publish -o linux-arm64 -c Release --self-contained true -r linux-arm64
        dotnet publish -o linux-x64 -c Release --self-contained true -r linux-x64
        dotnet publish -o win-x64 -c Release --self-contained true -r win-x64

    - name: Rename
      run: |
        mv linux-arm64/tldr-Discord linux-arm64/tldr-Discord-arm64
        mv linux-x64/tldr-Discord linux-x64/tldr-Discord-x64

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            linux-arm64/tldr-Discord-arm64          
            linux-x64/tldr-Discord-x64
            arm64/appsettings.json
            win-x64/tldr-Discord.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
