name: .NET

on:
  push:
    branches: [ master ]
  create:
    tags:
      - v*
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -o out -c Release --self-contained true -r linux-arm64
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: out/tldr-Discord
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
